name: aerogo
description: AeroGo Flutter app with role-based Go game menus.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  http: ^1.2.2
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/stone_click.wav
